name: Update Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
  workflow_dispatch: {}

permissions:
  packages: write

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: pognetwork
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - run: docker buildx build --platform linux/amd64,linux/arm64/v8 -t ghcr.io/pognetwork/dockerz:latest -f ./Dockerfile . --push
